version: '3.9'
services:
  db:
    image: mysql:8
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ms_db:/var/libs/ms_db
    networks:
      - ms_network
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ms17_demo'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
volumes:
  ms_db:
networks:
  ms_network:
#  ms:
#    image: 1234agil/ms17:1.1
#    restart: on-failure

