spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        show-sql: true