spring:
    profiles:
        active: local
        include:
            - common
            - db
            - security
            - logging

has:
    account: test
#server:
#  servlet:
#    context-path: api/v1/ms17-svc/